const router = require('express').Router();
const { getListings,getListing,createListing,updateListing,deleteListing,getMyListings } = require('../controllers/listingController');
const { protect, authorize } = require('../middleware/auth');
router.get('/', getListings);
router.get('/my', protect, getMyListings);
router.get('/:id', getListing);
router.post('/', protect, authorize('collector','business','admin'), createListing);
router.put('/:id', protect, updateListing);
router.delete('/:id', protect, deleteListing);
module.exports = router;
